// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using VoiceConcierge.Api.Data;

#nullable disable

namespace VoiceConcierge.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519162128_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VoiceConcierge.Api.Data.AppConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("app_config", (string)null);
                });

            modelBuilder.Entity("VoiceConcierge.Api.Data.FaqItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(384)")
                        .HasColumnName("embedding");

                    b.Property<string>("NormalizedQuestion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_question");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedQuestion")
                        .IsUnique();

                    b.ToTable("faq_items", (string)null);
                });

            modelBuilder.Entity("VoiceConcierge.Api.Data.UnansweredQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("FirstAskedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_asked_at");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer")
                        .HasColumnName("frequency");

                    b.Property<DateTimeOffset>("LastAskedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_asked_at");

                    b.Property<string>("NormalizedQuestion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_question");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedQuestion")
                        .IsUnique();

                    b.ToTable("unanswered_questions", (string)null);
                });

            modelBuilder.Entity("VoiceConcierge.Api.Data.Voice", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderVoiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_voice_id");

                    b.Property<string>("SampleText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sample_text");

                    b.HasKey("Id");

                    b.ToTable("voices", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
